/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class VaccionActu extends javax.swing.JFrame {

    int Mx, My;

    public VaccionActu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_Eliminar = new javax.swing.JPanel();
        lbl_Elimiar = new javax.swing.JLabel();
        pnl_Actualizar = new javax.swing.JPanel();
        lbl_Actualizar = new javax.swing.JLabel();
        pnl_Salir = new javax.swing.JPanel();
        lbl_Salir = new javax.swing.JLabel();
        lbl_Titulo = new javax.swing.JLabel();
        pnl_Barra = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_mregistro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_idclave = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Eliminar.setBackground(new java.awt.Color(136, 212, 234));

        lbl_Elimiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoEliminarAction.png"))); // NOI18N
        lbl_Elimiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ElimiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ElimiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ElimiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_EliminarLayout = new javax.swing.GroupLayout(pnl_Eliminar);
        pnl_Eliminar.setLayout(pnl_EliminarLayout);
        pnl_EliminarLayout.setHorizontalGroup(
            pnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Elimiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_EliminarLayout.setVerticalGroup(
            pnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Elimiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 140, 100));

        pnl_Actualizar.setBackground(new java.awt.Color(78, 184, 222));

        lbl_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoActualizarAction-.png"))); // NOI18N
        lbl_Actualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_ActualizarMouseMoved(evt);
            }
        });
        lbl_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_ActualizarLayout = new javax.swing.GroupLayout(pnl_Actualizar);
        pnl_Actualizar.setLayout(pnl_ActualizarLayout);
        pnl_ActualizarLayout.setHorizontalGroup(
            pnl_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_ActualizarLayout.setVerticalGroup(
            pnl_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 190));

        pnl_Salir.setBackground(new java.awt.Color(0, 93, 139));

        lbl_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSalirAction.png"))); // NOI18N
        lbl_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_SalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_SalirLayout = new javax.swing.GroupLayout(pnl_Salir);
        pnl_Salir.setLayout(pnl_SalirLayout);
        pnl_SalirLayout.setHorizontalGroup(
            pnl_SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_SalirLayout.setVerticalGroup(
            pnl_SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 140, 90));

        lbl_Titulo.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lbl_Titulo.setText("ACCIÓN A REALIZAR");
        jPanel1.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        pnl_Barra.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_BarraMouseDragged(evt);
            }
        });
        pnl_Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_BarraMousePressed(evt);
            }
        });

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minilogo.png"))); // NOI18N

        javax.swing.GroupLayout pnl_BarraLayout = new javax.swing.GroupLayout(pnl_Barra);
        pnl_Barra.setLayout(pnl_BarraLayout);
        pnl_BarraLayout.setHorizontalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BarraLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_BarraLayout.setVerticalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 370, 30));

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
        });
        jPanel1.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));
        jPanel1.add(lbl_mregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 10));

        lbl_idclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_idclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Mx, y - My);
    }//GEN-LAST:event_pnl_BarraMouseDragged

    private void pnl_BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMousePressed
        Mx = evt.getX();
        My = evt.getY();

    }//GEN-LAST:event_pnl_BarraMousePressed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered

    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_ActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ActualizarMouseEntered

      
        


    }//GEN-LAST:event_lbl_ActualizarMouseEntered

    private void lbl_ActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ActualizarMouseExited

       
       


    }//GEN-LAST:event_lbl_ActualizarMouseExited

    private void lbl_ElimiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ElimiarMouseEntered
        
       

    }//GEN-LAST:event_lbl_ElimiarMouseEntered

    private void lbl_ElimiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ElimiarMouseExited
       
       

    }//GEN-LAST:event_lbl_ElimiarMouseExited

    private void lbl_SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SalirMouseEntered

        
        

    }//GEN-LAST:event_lbl_SalirMouseEntered

    private void lbl_SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SalirMouseExited
        
       


    }//GEN-LAST:event_lbl_SalirMouseExited

    private void lbl_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ActualizarMouseClicked
       
    }//GEN-LAST:event_lbl_ActualizarMouseClicked

    private void lbl_ElimiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ElimiarMouseClicked
       
     
    }//GEN-LAST:event_lbl_ElimiarMouseClicked

    private void lbl_ActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ActualizarMouseMoved

    }//GEN-LAST:event_lbl_ActualizarMouseMoved

    private void lbl_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SalirMouseClicked
       
    }//GEN-LAST:event_lbl_SalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccionActu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccionActu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccionActu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccionActu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccionActu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbl_Actualizar;
    public javax.swing.JLabel lbl_Elimiar;
    public javax.swing.JLabel lbl_Salir;
    private javax.swing.JLabel lbl_Titulo;
    public javax.swing.JLabel lbl_exit;
    public javax.swing.JLabel lbl_idclave;
    private javax.swing.JLabel lbl_logo;
    public javax.swing.JLabel lbl_mregistro;
    public javax.swing.JPanel pnl_Actualizar;
    public javax.swing.JPanel pnl_Barra;
    public javax.swing.JPanel pnl_Eliminar;
    public javax.swing.JPanel pnl_Salir;
    // End of variables declaration//GEN-END:variables
}
