/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Vactualizar_Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Propietario
     */
    public Vactualizar_Vehiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_Color = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_Cilindraje = new javax.swing.JTextField();
        pnl_Registrar = new javax.swing.JPanel();
        lbl_Guardar = new javax.swing.JLabel();
        pnl_Volver = new javax.swing.JPanel();
        lbl_Volver = new javax.swing.JLabel();
        lbl_placaclave = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg_Vehiculos1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 170, 350));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Actualizar Vehiculo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Cilindraje:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Color:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 270, 10));

        txt_Color.setBorder(null);
        txt_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ColorActionPerformed(evt);
            }
        });
        txt_Color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ColorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 10));

        txt_Cilindraje.setBorder(null);
        txt_Cilindraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CilindrajeKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 270, -1));

        pnl_Registrar.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Guardar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Guardar.setText("Guardar");
        lbl_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_GuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_GuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_RegistrarLayout = new javax.swing.GroupLayout(pnl_Registrar);
        pnl_Registrar.setLayout(pnl_RegistrarLayout);
        pnl_RegistrarLayout.setHorizontalGroup(
            pnl_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_RegistrarLayout.setVerticalGroup(
            pnl_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 90, 30));

        pnl_Volver.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Volver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Volver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Volver.setText("Volver");
        lbl_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VolverLayout = new javax.swing.GroupLayout(pnl_Volver);
        pnl_Volver.setLayout(pnl_VolverLayout);
        pnl_VolverLayout.setHorizontalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_VolverLayout.setVerticalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 90, 30));

        lbl_placaclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_placaclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validarPlaca(JTextField txt) {
        String patron = "^[a-zA-Z]{3}-[0-9]{3}$";
        Pattern p = Pattern.compile(patron);
        Matcher m = p.matcher(txt.getText());
        return m.matches();
    }
    private void txt_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ColorActionPerformed

    private void txt_ColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ColorKeyTyped
 int key = evt.getKeyChar();
        boolean minuscula = key >= 65 && key <= 90;
        boolean mayuscula = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        if (!(minuscula || mayuscula || espacio)) {
            evt.consume();
        }
        if (txt_Color.getText().length() >= 20) {
            evt.consume();
        }  
    }//GEN-LAST:event_txt_ColorKeyTyped

    private void lbl_GuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GuardarMouseEntered
        
    }//GEN-LAST:event_lbl_GuardarMouseEntered

    private void lbl_GuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GuardarMouseExited
       
    }//GEN-LAST:event_lbl_GuardarMouseExited

    private void lbl_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseClicked
       
    }//GEN-LAST:event_lbl_VolverMouseClicked

    private void lbl_VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseEntered
       
    }//GEN-LAST:event_lbl_VolverMouseEntered

    private void lbl_VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseExited
        
    }//GEN-LAST:event_lbl_VolverMouseExited

    private void txt_CilindrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CilindrajeKeyTyped
       int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_Cilindraje.getText().length() >= 4) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_CilindrajeKeyTyped

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vactualizar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vactualizar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vactualizar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vactualizar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vactualizar_Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel lbl_Guardar;
    public javax.swing.JLabel lbl_Volver;
    public javax.swing.JLabel lbl_placaclave;
    public javax.swing.JPanel pnl_Registrar;
    public javax.swing.JPanel pnl_Volver;
    public javax.swing.JTextField txt_Cilindraje;
    public javax.swing.JTextField txt_Color;
    // End of variables declaration//GEN-END:variables
}
