/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author sebastian
 */
public class VBusqueda extends javax.swing.JFrame {

     int My,Mx;
    public VBusqueda() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnl_Barra.setBackground(new Color(255,255,255, 0));
        pnl_Barra.requestFocusInWindow();
        tbl_Busqueda.setVisible(false);
        Spnl_Busqueda.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_Barra = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_bgBusqueda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_Cc = new javax.swing.JTextField();
        pnl_Buscar = new javax.swing.JPanel();
        lbl_Buscar = new javax.swing.JLabel();
        Spnl_Busqueda = new javax.swing.JScrollPane();
        tbl_Busqueda = new javax.swing.JTable();
        pnl_Volver = new javax.swing.JPanel();
        lbl_Volver = new javax.swing.JLabel();
        pnl_Pdf = new javax.swing.JPanel();
        lbl_Pdf = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("BÚSQUEDA VEHICULOS");
        lbl_titulo.setToolTipText("");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 500, -1));

        pnl_Barra.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_BarraMouseDragged(evt);
            }
        });
        pnl_Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_BarraMousePressed(evt);
            }
        });

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minilogoSinfondo.png"))); // NOI18N

        javax.swing.GroupLayout pnl_BarraLayout = new javax.swing.GroupLayout(pnl_Barra);
        pnl_Barra.setLayout(pnl_BarraLayout);
        pnl_BarraLayout.setHorizontalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BarraLayout.createSequentialGroup()
                .addContainerGap(573, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_BarraLayout.setVerticalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        lbl_bgBusqueda.setBackground(new java.awt.Color(0, 153, 255));
        lbl_bgBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg2.png"))); // NOI18N
        jPanel1.add(lbl_bgBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 120));
        lbl_bgBusqueda.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("C.C. :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, 10));

        txt_Cc.setForeground(new java.awt.Color(204, 204, 204));
        txt_Cc.setText("Cédula");
        txt_Cc.setBorder(null);
        txt_Cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_CcMousePressed(evt);
            }
        });
        txt_Cc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CcKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 190, -1));

        pnl_Buscar.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Buscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbl_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoBotonBuscar.png"))); // NOI18N
        lbl_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_BuscarLayout = new javax.swing.GroupLayout(pnl_Buscar);
        pnl_Buscar.setLayout(pnl_BuscarLayout);
        pnl_BuscarLayout.setHorizontalGroup(
            pnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Buscar))
        );
        pnl_BuscarLayout.setVerticalGroup(
            pnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Buscar))
        );

        jPanel1.add(pnl_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 90, 30));

        Spnl_Busqueda.setBackground(new java.awt.Color(255, 255, 255));
        Spnl_Busqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_Busqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_Busqueda.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbl_Busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Tipo", "Modelo", "Color", "C.C.", "Marca", "Cilindraje", "Valor Comercial", "Combustible"
            }
        ));
        tbl_Busqueda.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Busqueda.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Spnl_Busqueda.setViewportView(tbl_Busqueda);

        jPanel1.add(Spnl_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 630, 190));

        pnl_Volver.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Volver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Volver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Volver.setText("Salir");
        lbl_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VolverLayout = new javax.swing.GroupLayout(pnl_Volver);
        pnl_Volver.setLayout(pnl_VolverLayout);
        pnl_VolverLayout.setHorizontalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_VolverLayout.setVerticalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 90, 30));

        pnl_Pdf.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Pdf.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Pdf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Pdf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Pdf.setText("PDF");
        lbl_Pdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PdfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PdfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PdfMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_PdfLayout = new javax.swing.GroupLayout(pnl_Pdf);
        pnl_Pdf.setLayout(pnl_PdfLayout);
        pnl_PdfLayout.setHorizontalGroup(
            pnl_PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PdfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_PdfLayout.setVerticalGroup(
            pnl_PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PdfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Mx, y - My);
    }//GEN-LAST:event_pnl_BarraMouseDragged

    private void pnl_BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMousePressed
        Mx = evt.getX();
        My = evt.getY();

    }//GEN-LAST:event_pnl_BarraMousePressed

    private void txt_CcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CcKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_Cc.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_CcKeyTyped

    private void txt_CcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CcMousePressed
       
    }//GEN-LAST:event_txt_CcMousePressed

    private void lbl_BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BuscarMouseExited

    }//GEN-LAST:event_lbl_BuscarMouseExited

    private void lbl_BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BuscarMouseEntered
     
    }//GEN-LAST:event_lbl_BuscarMouseEntered

    private void lbl_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BuscarMouseClicked

     
       
    }//GEN-LAST:event_lbl_BuscarMouseClicked

    private void lbl_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseClicked
        
    }//GEN-LAST:event_lbl_VolverMouseClicked

    private void lbl_VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseEntered
        pnl_Volver.setBackground(new Color(0,181,255));
    }//GEN-LAST:event_lbl_VolverMouseEntered

    private void lbl_VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseExited
       
    }//GEN-LAST:event_lbl_VolverMouseExited

    private void lbl_PdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PdfMouseClicked
    
    }//GEN-LAST:event_lbl_PdfMouseClicked

    private void lbl_PdfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PdfMouseEntered
        
    }//GEN-LAST:event_lbl_PdfMouseEntered

    private void lbl_PdfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PdfMouseExited
        
    }//GEN-LAST:event_lbl_PdfMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane Spnl_Busqueda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbl_Buscar;
    public javax.swing.JLabel lbl_Pdf;
    public javax.swing.JLabel lbl_Volver;
    public javax.swing.JLabel lbl_bgBusqueda;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_titulo;
    public javax.swing.JPanel pnl_Barra;
    public javax.swing.JPanel pnl_Buscar;
    public javax.swing.JPanel pnl_Pdf;
    public javax.swing.JPanel pnl_Volver;
    public javax.swing.JTable tbl_Busqueda;
    public javax.swing.JTextField txt_Cc;
    // End of variables declaration//GEN-END:variables
}
