/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author sebastian
 */
public class VInformeAnual extends javax.swing.JFrame {

     int My,Mx;
    public VInformeAnual() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnl_Barra.setBackground(new Color(255,255,255, 0));
        pnl_Barra.requestFocusInWindow();
        tbl_Ianual.setVisible(false);
        Spnl_Ianual.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_Barra = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_bgBusqueda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_Buscar = new javax.swing.JPanel();
        lbl_Generar = new javax.swing.JLabel();
        Spnl_Ianual = new javax.swing.JScrollPane();
        tbl_Ianual = new javax.swing.JTable();
        pnl_Volver = new javax.swing.JPanel();
        lbl_Volver = new javax.swing.JLabel();
        pnl_Pdf = new javax.swing.JPanel();
        lbl_Pdf = new javax.swing.JLabel();
        txt_anio = new javax.swing.JTextField();

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Informe Por Año");
        lbl_titulo.setToolTipText("");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        pnl_Barra.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_BarraMouseDragged(evt);
            }
        });
        pnl_Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_BarraMousePressed(evt);
            }
        });

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minilogoSinfondo.png"))); // NOI18N

        javax.swing.GroupLayout pnl_BarraLayout = new javax.swing.GroupLayout(pnl_Barra);
        pnl_Barra.setLayout(pnl_BarraLayout);
        pnl_BarraLayout.setHorizontalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BarraLayout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_BarraLayout.setVerticalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 30));

        lbl_bgBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg2.png"))); // NOI18N
        jPanel1.add(lbl_bgBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Año:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 10));

        pnl_Buscar.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Generar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Generar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Generar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Generar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Generar.setText("Generar");
        lbl_Generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_GenerarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_GenerarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_GenerarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_BuscarLayout = new javax.swing.GroupLayout(pnl_Buscar);
        pnl_Buscar.setLayout(pnl_BuscarLayout);
        pnl_BuscarLayout.setHorizontalGroup(
            pnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Generar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        pnl_BuscarLayout.setVerticalGroup(
            pnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Generar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 90, 30));

        Spnl_Ianual.setBackground(new java.awt.Color(255, 255, 255));
        Spnl_Ianual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_Ianual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_Ianual.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbl_Ianual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIT", "Placa", "Año", "Valor"
            }
        ));
        tbl_Ianual.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Ianual.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Spnl_Ianual.setViewportView(tbl_Ianual);

        jPanel1.add(Spnl_Ianual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 490, 190));

        pnl_Volver.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Volver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Volver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Volver.setText("Salir");
        lbl_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VolverLayout = new javax.swing.GroupLayout(pnl_Volver);
        pnl_Volver.setLayout(pnl_VolverLayout);
        pnl_VolverLayout.setHorizontalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_VolverLayout.setVerticalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 90, 30));

        pnl_Pdf.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Pdf.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Pdf.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Pdf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Pdf.setText("PDF");
        lbl_Pdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PdfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PdfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PdfMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_PdfLayout = new javax.swing.GroupLayout(pnl_Pdf);
        pnl_Pdf.setLayout(pnl_PdfLayout);
        pnl_PdfLayout.setHorizontalGroup(
            pnl_PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PdfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_PdfLayout.setVerticalGroup(
            pnl_PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PdfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 90, 30));

        txt_anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_anio.setBorder(null);
        txt_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_anioKeyTyped(evt);
            }
        });
        jPanel1.add(txt_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Mx, y - My);
    }//GEN-LAST:event_pnl_BarraMouseDragged

    private void pnl_BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMousePressed
        Mx = evt.getX();
        My = evt.getY();

    }//GEN-LAST:event_pnl_BarraMousePressed

    private void lbl_GenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GenerarMouseExited
       
    }//GEN-LAST:event_lbl_GenerarMouseExited

    private void lbl_GenerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GenerarMouseEntered
      
    }//GEN-LAST:event_lbl_GenerarMouseEntered

    private void lbl_GenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GenerarMouseClicked

       
    }//GEN-LAST:event_lbl_GenerarMouseClicked

    private void lbl_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseClicked
       
    }//GEN-LAST:event_lbl_VolverMouseClicked

    private void lbl_VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseEntered
       
    }//GEN-LAST:event_lbl_VolverMouseEntered

    private void lbl_VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseExited
       
    }//GEN-LAST:event_lbl_VolverMouseExited

    private void lbl_PdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PdfMouseClicked
    
    }//GEN-LAST:event_lbl_PdfMouseClicked

    private void lbl_PdfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PdfMouseEntered
       
    }//GEN-LAST:event_lbl_PdfMouseEntered

    private void lbl_PdfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PdfMouseExited
        
    }//GEN-LAST:event_lbl_PdfMouseExited

    private void txt_anioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_anioKeyTyped
       int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_anio.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_anioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VInformeAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VInformeAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VInformeAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VInformeAnual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VInformeAnual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane Spnl_Ianual;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbl_Generar;
    public javax.swing.JLabel lbl_Pdf;
    public javax.swing.JLabel lbl_Volver;
    public javax.swing.JLabel lbl_bgBusqueda;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_titulo;
    public javax.swing.JPanel pnl_Barra;
    public javax.swing.JPanel pnl_Buscar;
    public javax.swing.JPanel pnl_Pdf;
    public javax.swing.JPanel pnl_Volver;
    public javax.swing.JTable tbl_Ianual;
    public javax.swing.JTextField txt_anio;
    // End of variables declaration//GEN-END:variables
}
