/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class VmenuActualizar extends javax.swing.JFrame {

    int Mx, My;

    public VmenuActualizar() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_Vehiculo = new javax.swing.JPanel();
        lbl_Vehiculo = new javax.swing.JLabel();
        pnl_Propietario = new javax.swing.JPanel();
        lbl_Propietario = new javax.swing.JLabel();
        pnl_Volver = new javax.swing.JPanel();
        lbl_Volver = new javax.swing.JLabel();
        pnl_AgregarV = new javax.swing.JPanel();
        lbl_AgregarV = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_Titulo = new javax.swing.JLabel();
        pnl_Barra = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_mregistro = new javax.swing.JLabel();
        lbl_idclave = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Vehiculo.setBackground(new java.awt.Color(136, 212, 234));

        lbl_Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVehiculo.png"))); // NOI18N
        lbl_Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VehiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VehiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VehiculoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VehiculoLayout = new javax.swing.GroupLayout(pnl_Vehiculo);
        pnl_Vehiculo.setLayout(pnl_VehiculoLayout);
        pnl_VehiculoLayout.setHorizontalGroup(
            pnl_VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Vehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_VehiculoLayout.setVerticalGroup(
            pnl_VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Vehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 100));

        pnl_Propietario.setBackground(new java.awt.Color(78, 184, 222));

        lbl_Propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPropietario.png"))); // NOI18N
        lbl_Propietario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_PropietarioMouseMoved(evt);
            }
        });
        lbl_Propietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PropietarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PropietarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PropietarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_PropietarioLayout = new javax.swing.GroupLayout(pnl_Propietario);
        pnl_Propietario.setLayout(pnl_PropietarioLayout);
        pnl_PropietarioLayout.setHorizontalGroup(
            pnl_PropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Propietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_PropietarioLayout.setVerticalGroup(
            pnl_PropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Propietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 190));

        pnl_Volver.setBackground(new java.awt.Color(0, 93, 139));

        lbl_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSalirAction.png"))); // NOI18N
        lbl_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VolverLayout = new javax.swing.GroupLayout(pnl_Volver);
        pnl_Volver.setLayout(pnl_VolverLayout);
        pnl_VolverLayout.setHorizontalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_VolverLayout.setVerticalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 140, 90));

        pnl_AgregarV.setBackground(new java.awt.Color(0, 134, 190));

        lbl_AgregarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoAgregarV.png"))); // NOI18N
        lbl_AgregarV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AgregarVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_AgregarVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_AgregarVMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_AgregarVLayout = new javax.swing.GroupLayout(pnl_AgregarV);
        pnl_AgregarV.setLayout(pnl_AgregarVLayout);
        pnl_AgregarVLayout.setHorizontalGroup(
            pnl_AgregarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_AgregarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_AgregarVLayout.setVerticalGroup(
            pnl_AgregarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_AgregarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_AgregarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 340, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 10));

        lbl_Titulo.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        lbl_Titulo.setText("ACTUALIZAR");
        jPanel1.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pnl_Barra.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_BarraMouseDragged(evt);
            }
        });
        pnl_Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_BarraMousePressed(evt);
            }
        });

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minilogo.png"))); // NOI18N

        javax.swing.GroupLayout pnl_BarraLayout = new javax.swing.GroupLayout(pnl_Barra);
        pnl_Barra.setLayout(pnl_BarraLayout);
        pnl_BarraLayout.setHorizontalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BarraLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_BarraLayout.setVerticalGroup(
            pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 370, 30));

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setText("X");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
        });
        jPanel1.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));
        jPanel1.add(lbl_mregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lbl_idclave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_idclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Mx, y - My);
    }//GEN-LAST:event_pnl_BarraMouseDragged

    private void pnl_BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_BarraMousePressed
        Mx = evt.getX();
        My = evt.getY();

    }//GEN-LAST:event_pnl_BarraMousePressed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered

    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_PropietarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropietarioMouseEntered

       



    }//GEN-LAST:event_lbl_PropietarioMouseEntered

    private void lbl_PropietarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropietarioMouseExited

        
        


    }//GEN-LAST:event_lbl_PropietarioMouseExited

    private void lbl_VehiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VehiculoMouseEntered
       
       
    }//GEN-LAST:event_lbl_VehiculoMouseEntered

    private void lbl_VehiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VehiculoMouseExited
        
       

    }//GEN-LAST:event_lbl_VehiculoMouseExited

    private void lbl_VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseEntered

        
       

    }//GEN-LAST:event_lbl_VolverMouseEntered

    private void lbl_VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseExited
      
       
       


    }//GEN-LAST:event_lbl_VolverMouseExited

    private void lbl_AgregarVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AgregarVMouseEntered
        
       
    }//GEN-LAST:event_lbl_AgregarVMouseEntered

    private void lbl_PropietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropietarioMouseClicked
     
    }//GEN-LAST:event_lbl_PropietarioMouseClicked

    private void lbl_VehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VehiculoMouseClicked

       
    }//GEN-LAST:event_lbl_VehiculoMouseClicked

    private void lbl_AgregarVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AgregarVMouseExited
        
        
       
    }//GEN-LAST:event_lbl_AgregarVMouseExited
    private void lbl_PropietarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropietarioMouseMoved

    }//GEN-LAST:event_lbl_PropietarioMouseMoved

    private void lbl_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseClicked
      
    }//GEN-LAST:event_lbl_VolverMouseClicked

    private void lbl_AgregarVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AgregarVMouseClicked

    }//GEN-LAST:event_lbl_AgregarVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VmenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VmenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VmenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VmenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VmenuActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbl_AgregarV;
    public javax.swing.JLabel lbl_Propietario;
    private javax.swing.JLabel lbl_Titulo;
    public javax.swing.JLabel lbl_Vehiculo;
    public javax.swing.JLabel lbl_Volver;
    public javax.swing.JLabel lbl_exit;
    public javax.swing.JLabel lbl_idclave;
    private javax.swing.JLabel lbl_logo;
    public javax.swing.JLabel lbl_mregistro;
    public javax.swing.JPanel pnl_AgregarV;
    public javax.swing.JPanel pnl_Barra;
    public javax.swing.JPanel pnl_Propietario;
    public javax.swing.JPanel pnl_Vehiculo;
    public javax.swing.JPanel pnl_Volver;
    // End of variables declaration//GEN-END:variables
}
