/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Vregistro_Comparendos extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Propietario
     */
    public Vregistro_Comparendos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Nombres = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_radicado = new javax.swing.JTextField();
        txt_Cc = new javax.swing.JTextField();
        txt_Valor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        dc_Fecha = new com.toedter.calendar.JDateChooser();
        pnl_Volver = new javax.swing.JPanel();
        lbl_Volver = new javax.swing.JLabel();
        pnl_Registrar = new javax.swing.JPanel();
        lbl_Registrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtp_descrip = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox<>();

        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diseño sin título.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 170, 470));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Registro Comparendos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 60));

        lbl_Nombres.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_Nombres.setText("Radicado");
        jPanel1.add(lbl_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("C.C. :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Fecha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Descripcion:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 20));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Estado");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 20));

        txt_radicado.setBorder(null);
        txt_radicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_radicadoActionPerformed(evt);
            }
        });
        txt_radicado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_radicadoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_radicado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 270, -1));

        txt_Cc.setBorder(null);
        txt_Cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CcActionPerformed(evt);
            }
        });
        txt_Cc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CcKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, -1));

        txt_Valor.setBorder(null);
        txt_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ValorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 270, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 270, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 270, 10));

        dc_Fecha.setRequestFocusEnabled(false);
        jPanel1.add(dc_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 20));

        pnl_Volver.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Volver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Volver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Volver.setText("Volver");
        lbl_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VolverLayout = new javax.swing.GroupLayout(pnl_Volver);
        pnl_Volver.setLayout(pnl_VolverLayout);
        pnl_VolverLayout.setHorizontalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_VolverLayout.setVerticalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 90, 30));

        pnl_Registrar.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Registrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Registrar.setText("Registrar");
        lbl_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_RegistrarLayout = new javax.swing.GroupLayout(pnl_Registrar);
        pnl_Registrar.setLayout(pnl_RegistrarLayout);
        pnl_RegistrarLayout.setHorizontalGroup(
            pnl_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_RegistrarLayout.setVerticalGroup(
            pnl_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 90, 30));

        jScrollPane1.setViewportView(txtp_descrip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 270, 50));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Valor: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGO", "EN MORA", "PAGANDO" }));
        jPanel1.add(cmb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_radicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_radicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_radicadoActionPerformed

    private void txt_CcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CcKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_Cc.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_CcKeyTyped

    private void txt_radicadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_radicadoKeyTyped
        int key = evt.getKeyChar();
        boolean minuscula = key >= 65 && key <= 90;
        boolean mayuscula = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        if (!(minuscula || mayuscula || espacio)) {
            evt.consume();
        }
        if (txt_radicado.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_radicadoKeyTyped

    private void txt_CcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CcActionPerformed

    private void txt_ValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ValorKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_Valor.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ValorKeyTyped

    private void lbl_VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseEntered

    }//GEN-LAST:event_lbl_VolverMouseEntered

    private void lbl_VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseExited

    }//GEN-LAST:event_lbl_VolverMouseExited

    private void lbl_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseClicked

    }//GEN-LAST:event_lbl_VolverMouseClicked

    private void lbl_RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseEntered
       

    }//GEN-LAST:event_lbl_RegistrarMouseEntered

    private void lbl_RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseExited
     
    }//GEN-LAST:event_lbl_RegistrarMouseExited

    private void lbl_RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseClicked

    }//GEN-LAST:event_lbl_RegistrarMouseClicked

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Comparendos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Comparendos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Comparendos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Comparendos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vregistro_Comparendos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmb_estado;
    public com.toedter.calendar.JDateChooser dc_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JLabel lbl_Nombres;
    public javax.swing.JLabel lbl_Registrar;
    public javax.swing.JLabel lbl_Volver;
    public javax.swing.JPanel pnl_Registrar;
    public javax.swing.JPanel pnl_Volver;
    public javax.swing.JTextField txt_Cc;
    public javax.swing.JTextField txt_Valor;
    public javax.swing.JTextField txt_radicado;
    public javax.swing.JTextPane txtp_descrip;
    // End of variables declaration//GEN-END:variables
}
