
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Vregistro_Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Propietario
     */
    public Vregistro_Vehiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Email = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Placa = new javax.swing.JLabel();
        lbl_Tipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Placa = new javax.swing.JTextField();
        txt_Modelo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        cmb_Tipo = new javax.swing.JComboBox<>();
        txt_Color = new javax.swing.JTextField();
        txt_Marca = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txt_ValorComercial = new javax.swing.JTextField();
        lbl_irWeb = new javax.swing.JLabel();
        txt_Cilindraje = new javax.swing.JTextField();
        pnl_Volver = new javax.swing.JPanel();
        lbl_Volver = new javax.swing.JLabel();
        pnl_Registrar = new javax.swing.JPanel();
        lbl_Registrar = new javax.swing.JLabel();
        lbl_idclave = new javax.swing.JLabel();
        lbl_combus = new javax.swing.JLabel();
        cmb_combus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jyc_anioR = new com.toedter.calendar.JYearChooser();

        txt_Email.setBorder(null);
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });

        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg_Vehiculos1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 170, 490));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Registro Vehiculo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Cilindraje:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 20));

        lbl_Placa.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_Placa.setText("Placa:");
        jPanel1.add(lbl_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        lbl_Tipo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_Tipo.setText("Tipo: ");
        jPanel1.add(lbl_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Modelo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Marca:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Color:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 20));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Año de Registro:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        txt_Placa.setBorder(null);
        txt_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PlacaActionPerformed(evt);
            }
        });
        txt_Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PlacaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, 20));

        txt_Modelo.setBorder(null);
        txt_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ModeloActionPerformed(evt);
            }
        });
        txt_Modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ModeloKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 186, 270, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 270, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 270, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 270, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 110, 10));

        cmb_Tipo.setEditable(true);
        cmb_Tipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Publico" }));
        cmb_Tipo.setSelectedItem("");
        cmb_Tipo.setBorder(null);
        cmb_Tipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(cmb_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 20));

        txt_Color.setBorder(null);
        txt_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ColorActionPerformed(evt);
            }
        });
        txt_Color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ColorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 270, 20));

        txt_Marca.setBorder(null);
        txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MarcaActionPerformed(evt);
            }
        });
        txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MarcaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 270, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 270, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 270, 10));

        txt_ValorComercial.setBorder(null);
        txt_ValorComercial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ValorComercialKeyTyped(evt);
            }
        });
        jPanel1.add(txt_ValorComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 20));

        lbl_irWeb.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lbl_irWeb.setText("¿no sabes el valor comercial de tu auto?");
        lbl_irWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_irWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_irWebMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_irWebMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_irWebMouseExited(evt);
            }
        });
        jPanel1.add(lbl_irWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        txt_Cilindraje.setBorder(null);
        txt_Cilindraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CilindrajeKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 270, -1));

        pnl_Volver.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Volver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Volver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Volver.setText("Volver");
        lbl_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_VolverLayout = new javax.swing.GroupLayout(pnl_Volver);
        pnl_Volver.setLayout(pnl_VolverLayout);
        pnl_VolverLayout.setHorizontalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_VolverLayout.setVerticalGroup(
            pnl_VolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_VolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 90, 30));

        pnl_Registrar.setBackground(new java.awt.Color(0, 153, 255));

        lbl_Registrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Registrar.setText("Registrar");
        lbl_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_RegistrarLayout = new javax.swing.GroupLayout(pnl_Registrar);
        pnl_Registrar.setLayout(pnl_RegistrarLayout);
        pnl_RegistrarLayout.setHorizontalGroup(
            pnl_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_RegistrarLayout.setVerticalGroup(
            pnl_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 90, 30));
        jPanel1.add(lbl_idclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, 20));

        lbl_combus.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_combus.setText("Combustible:");
        jPanel1.add(lbl_combus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        cmb_combus.setEditable(true);
        cmb_combus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_combus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Diesel", "Gas", "Hibrido", "Electrico" }));
        cmb_combus.setSelectedItem("");
        cmb_combus.setBorder(null);
        cmb_combus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_combus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_combusActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_combus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, 20));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Valor Comercial:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 20));
        jPanel1.add(jyc_anioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PlacaActionPerformed

    private void txt_ModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ModeloKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_Modelo.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ModeloKeyTyped

    private void txt_PlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PlacaKeyTyped

        if (txt_Placa.getText().length() >= 7) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_PlacaKeyTyped

    private void txt_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ModeloActionPerformed
   
    private void txt_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ColorActionPerformed

    private void txt_ColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ColorKeyTyped
      int key = evt.getKeyChar();
        boolean minuscula = key >= 65 && key <= 90;
        boolean mayuscula = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        if (!(minuscula || mayuscula || espacio)) {
            evt.consume();
        }
        if (txt_Color.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ColorKeyTyped

    private void txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MarcaActionPerformed

    private void txt_MarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MarcaKeyTyped
   int key = evt.getKeyChar();
        boolean minuscula = key >= 65 && key <= 90;
        boolean mayuscula = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        if (!(minuscula || mayuscula || espacio)) {
            evt.consume();
        }
        if (txt_Marca.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_MarcaKeyTyped
    private void lbl_irWebMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_irWebMouseEntered
        
      }//GEN-LAST:event_lbl_irWebMouseEntered

    private void lbl_irWebMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_irWebMouseExited
        
    }//GEN-LAST:event_lbl_irWebMouseExited

    private void lbl_irWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_irWebMouseClicked
        
    }//GEN-LAST:event_lbl_irWebMouseClicked

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void lbl_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseClicked
        
    }//GEN-LAST:event_lbl_VolverMouseClicked

    private void lbl_VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseEntered
      
    }//GEN-LAST:event_lbl_VolverMouseEntered

    private void lbl_VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_VolverMouseExited
       
    }//GEN-LAST:event_lbl_VolverMouseExited

    private void lbl_RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseEntered
       
    }//GEN-LAST:event_lbl_RegistrarMouseEntered

    private void lbl_RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseExited
       
    }//GEN-LAST:event_lbl_RegistrarMouseExited

    private void lbl_RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseClicked
       

    }//GEN-LAST:event_lbl_RegistrarMouseClicked

    private void cmb_combusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_combusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_combusActionPerformed

    private void txt_CilindrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CilindrajeKeyTyped
 int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_Cilindraje.getText().length() >= 10) {
            evt.consume();
        }      
    }//GEN-LAST:event_txt_CilindrajeKeyTyped

    private void txt_ValorComercialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ValorComercialKeyTyped
     int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (txt_ValorComercial.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ValorComercialKeyTyped

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vregistro_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vregistro_Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmb_Tipo;
    public javax.swing.JComboBox<String> cmb_combus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public com.toedter.calendar.JYearChooser jyc_anioR;
    public javax.swing.JLabel lbl_Placa;
    public javax.swing.JLabel lbl_Registrar;
    public javax.swing.JLabel lbl_Tipo;
    public javax.swing.JLabel lbl_Volver;
    public javax.swing.JLabel lbl_combus;
    public javax.swing.JLabel lbl_idclave;
    public javax.swing.JLabel lbl_irWeb;
    public javax.swing.JPanel pnl_Registrar;
    public javax.swing.JPanel pnl_Volver;
    public javax.swing.JTextField txt_Cilindraje;
    public javax.swing.JTextField txt_Color;
    public javax.swing.JTextField txt_Email;
    public javax.swing.JTextField txt_Marca;
    public javax.swing.JTextField txt_Modelo;
    public javax.swing.JTextField txt_Placa;
    public javax.swing.JTextField txt_ValorComercial;
    // End of variables declaration//GEN-END:variables
}
